FROM mysql:8.0


# Copier les scripts d'initialisation
COPY ./setup-replica.sh  /docker-entrypoint-initdb.d/

# Donner les permissions d'exécution
RUN chmod +x  /docker-entrypoint-initdb.d/setup-replica.sh
