#!/bin/bash
### SCRIPT BASH GENERATED BY mygenconf.py at 2021-06-09 18:07:40.466931
source ../profile

### COMMAND TO CREATE LINODES
lcreate elk_elksrv eixo1hoo7Goo7suu9v ./id_rsa.pub application webapps linux
lcreate elk_pgsrv1 eixo1hoo7Goo7suu9v ./id_rsa.pub postgresql postgres database linux
lcreate elk_pgsrv2 eixo1hoo7Goo7suu9v ./id_rsa.pub postgresql postgres database linux
