#!/usr/bin/env python3

import sys
import datetime
from config import defaults, merge_params,get_public_ip


def generate_create_script(_metaconf):
    if 'genscript_name' in _metaconf.keys():
        _metaconf['out']=open(_metaconf['generic_prefix']+'_' +_metaconf['genscript_name'], "w")
    else:
        _metaconf['out']=sys.stdout
    print("""#!/bin/bash
### SCRIPT BASH GENERATED BY mygenconf.py at {datetime}
source ../profile""".format(**_metaconf), file=_metaconf['out'])

    print("""
### COMMAND TO CREATE LINODES""", file=_metaconf['out'])

    for i in range(1, _metaconf['nb_linode_vms'] + 1):
        _metaconf['current_vm_name']=_metaconf['generic_prefix'] + '_' + _metaconf['vm_name_'+str(i)];
        _metaconf['current_tags']=_metaconf['vm_tags_'+str(i)].replace(',', ' ');
        print("""lcreate {current_vm_name} {vm_generic_password} {vm_generic_pubkey} {current_tags}""".format(**_metaconf), file=_metaconf['out'])

    if _metaconf['out']!=sys.stdout:
        _metaconf['out'].close()

def generate_drop_script(_metaconf):
    if 'genscript_name' in _metaconf.keys():
        _metaconf['out']=open(_metaconf['generic_prefix']+'_' +_metaconf['delscript_name'], "w")
    else:
        _metaconf['out']=sys.stdout
    print("""#!/bin/bash
### SCRIPT BASH GENERATED BY mygenconf.py at {datetime}
source ../profile""", file=_metaconf['out'])

    for i in range(1, _metaconf['nb_linode_vms'] + 1):
        _metaconf['current_vm_name']=_metaconf['generic_prefix'] +'_' + _metaconf['vm_name_'+str(i)];
        _metaconf['current_tags']=_metaconf['vm_tags_'+str(i)].replace(',', ' ');
        print("""ldelete {current_vm_name}""".format(**_metaconf), file=_metaconf['out'])

    if _metaconf['out']!=sys.stdout:
        _metaconf['out'].close()

def generate_drop_script(_metaconf):
    if 'genscript_name' in _metaconf.keys():
        _metaconf['out']=open(_metaconf['generic_prefix']+'_' +_metaconf['delscript_name'], "w")
    else:
        _metaconf['out']=sys.stdout
    print("""#!/bin/bash
### SCRIPT BASH GENERATED BY mygenconf.py at {datetime}
source ../profile""", file=_metaconf['out'])

    for i in range(1, _metaconf['nb_linode_vms'] + 1):
        _metaconf['current_vm_name']=_metaconf['generic_prefix'] +'_' + _metaconf['vm_name_'+str(i)];
        _metaconf['current_tags']=_metaconf['vm_tags_'+str(i)].replace(',', ' ');
        print("""ldelete {current_vm_name}""".format(**_metaconf), file=_metaconf['out'])

    if _metaconf['out']!=sys.stdout:
        _metaconf['out'].close()


def main(argv):
    params=merge_params(defaults, argv)
    generate_create_script(params)
    generate_drop_script(params)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))