#!/usr/bin/env python3

import sys
import datetime
from config import defaults, merge_params,get_public_ip
from shell import Shell

def generate_bat_script(name, ip, user="root", private_key="./id_rsa.ppk"):
    outputFile="putty_%s.bat" % name
    with open(outputFile, 'w') as script:
        print(f"""echo Starting {name} Putty connexion TO {name} Virtual VM
putty.exe -ssh -v -l {user} -i {private_key} {ip}""", file=script)


def generate_bat_scripts(_metaconf):
    for i in range(1, _metaconf['nb_linode_vms']+1):
        lname=_metaconf['generic_prefix'] +'_' + _metaconf['vm_name_'+str(i)];
        lpip=get_public_ip(lname)
        print(lname + ' => ' + lpip)
        generate_bat_script(lname, lpip)

def generate_provisionning_script(_metaconf):
    if 'genscript_name' in _metaconf.keys():
        _metaconf['out']=open(_metaconf['generic_prefix']+'_' +_metaconf['provscript_name'], "w")
    else:
        _metaconf['out']=sys.stdout
    print("""#!/bin/bash
### SCRIPT BASH GENERATED BY mygenconf.py at {datetime}
source ../profile""".format(**_metaconf), file=_metaconf['out'])

    print("""
### COMMAND TO GENERATE /etc/hosts file
lgenHosts {generic_prefix}""".format(**_metaconf), file=_metaconf['out'])

    print("""
### COMMAND TO GENERATE /etc/hosts file""".format(**_metaconf), file=_metaconf['out'])

    for i in range(1, _metaconf['nb_linode_vms']+1):
        lname=_metaconf['generic_prefix'] +'_' + _metaconf['vm_name_'+str(i)];
        _metaconf['current_vm_name']=lname
        _metaconf['current_public_ip']=get_public_ip(lname)
        print("""ssh root@{current_public_ip} "hostnamectl set-hostname {current_vm_name}"
scp {generic_prefix}generated_hosts root@{current_public_ip}:/etc/hosts
ssh root@{current_public_ip} "chmod 644 /etc/hosts"
scp id_rsa id_rsa.pub root@{current_public_ip}:/root/.ssh
ssh root@{current_public_ip} "chmod -R 600 /root/.ssh/id_rsa"
scp ../scripts/utils.sh root@{current_public_ip}:/etc/profile.d
ssh root@{current_public_ip} "chmod 755 /etc/profile.d/utils.sh"
ssh root@{current_public_ip} "dnf -y install git rsync perl"

""".format(**_metaconf), file=_metaconf['out'])

    if i == _metaconf['nb_linode_vms']:
        print("""ssh root@{current_public_ip} "git clone https://github.com/jmrenouard/dbscripts.git"
        	""".format(**_metaconf), file=_metaconf['out'])


def main(argv):
    params=merge_params(defaults, argv)

    generate_bat_scripts(params)
    generate_provisionning_script(params)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))